# Water Level Sensor Configuration Integration
# Add these lines to your main configuration.yaml file

# Include automations for water level monitoring
automation: !include automations/water_level_sensor_automations.yaml

# Include template sensors for water level monitoring
template: !include templates/water_level_sensor_templates.yaml

# Optional: If you want to include the dashboard views in your main configuration
# (Alternative: Import the dashboard separately in Lovelace)
# lovelace:
#   mode: yaml
#   dashboards:
#     water-level:
#       mode: yaml
#       title: Water Level Monitoring
#       icon: mdi:water
#       show_in_sidebar: true
#       source: !include lovelace/water_level_dashboard.yaml 