# Water Level Sensor Template Sensors
# This file contains all template sensors for the water level monitoring system
# Add this to your configuration.yaml with: template: !include templates/water_level_sensor_templates.yaml

- sensor:
    # 3rd Floor Tank Template Sensors
    - name: "3rd Floor Days Until Empty"
      unique_id: "water_days_until_empty_3f"
      state: >
        {% set water_sensor = states.sensor.water_level_3f %}
        {% if water_sensor is not none %}
          {% set current_level = states('sensor.water_level_3f') | float(0) %}
          {% set daily_usage = water_sensor.attributes.get('average_daily_consumption_l_day', 0) | float(0) %}
          {% if daily_usage > 0 and current_level > 0 %}
            {% set current_volume = water_sensor.attributes.get('volume_liters', 0) | float(0) %}
            {{ (current_volume / daily_usage) | round(1) }}
          {% else %}
            0
          {% endif %}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: "d"
      device_class: "duration"
      
    - name: "3rd Floor Water Usage Trend"
      unique_id: "water_usage_trend_3f"
      state: >
        {% set water_sensor = states.sensor.water_level_3f %}
        {% if water_sensor is not none %}
          {% set current_usage = water_sensor.attributes.get('hourly_consumption_l_hour', 0) | float(0) %}
          {% set avg_usage = water_sensor.attributes.get('average_daily_consumption_l_day', 0) | float(0) / 24 %}
          {% if avg_usage > 0 %}
            {% if current_usage > avg_usage * 1.5 %}
              High
            {% elif current_usage < avg_usage * 0.5 %}
              Low
            {% else %}
              Normal
            {% endif %}
          {% else %}
            Normal
          {% endif %}
        {% else %}
          Normal
        {% endif %}
      device_class: "enum"
      
    - name: "3rd Floor Leak Severity"
      unique_id: "water_leak_severity_3f"
      state: >
        {% set water_sensor = states.sensor.water_level_3f %}
        {% if water_sensor is not none %}
          {% set rapid_leak = water_sensor.attributes.get('consumption_15min_l_15min', 0) | float(0) %}
          {% set moderate_leak = water_sensor.attributes.get('consumption_30min_l_30min', 0) | float(0) %}
          {% set rapid_threshold = states('input_number.rapid_leak_threshold_tank_3f') | default(5.0) | float(5.0) %}
          {% set moderate_threshold = states('input_number.moderate_leak_threshold_tank_3f') | default(8.0) | float(8.0) %}
          {% if rapid_leak > rapid_threshold %}
            Critical
          {% elif moderate_leak > moderate_threshold %}
            Moderate
          {% else %}
            None
          {% endif %}
        {% else %}
          None
        {% endif %}
      device_class: "enum"
      
    # 1st Floor Tank Template Sensors
    - name: "1st Floor Days Until Empty"
      unique_id: "water_days_until_empty_1f"
      state: >
        {% set water_sensor = states.sensor.water_level_1f %}
        {% if water_sensor is not none %}
          {% set current_level = states('sensor.water_level_1f') | float(0) %}
          {% set daily_usage = water_sensor.attributes.get('average_daily_consumption_l_day', 0) | float(0) %}
          {% if daily_usage > 0 and current_level > 0 %}
            {% set current_volume = water_sensor.attributes.get('volume_liters', 0) | float(0) %}
            {{ (current_volume / daily_usage) | round(1) }}
          {% else %}
            0
          {% endif %}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: "d"
      device_class: "duration"
      
    - name: "1st Floor Water Usage Trend"
      unique_id: "water_usage_trend_1f"
      state: >
        {% set water_sensor = states.sensor.water_level_1f %}
        {% if water_sensor is not none %}
          {% set current_usage = water_sensor.attributes.get('hourly_consumption_l_hour', 0) | float(0) %}
          {% set avg_usage = water_sensor.attributes.get('average_daily_consumption_l_day', 0) | float(0) / 24 %}
          {% if avg_usage > 0 %}
            {% if current_usage > avg_usage * 1.5 %}
              High
            {% elif current_usage < avg_usage * 0.5 %}
              Low
            {% else %}
              Normal
            {% endif %}
          {% else %}
            Normal
          {% endif %}
        {% else %}
          Normal
        {% endif %}
      device_class: "enum"
      
    - name: "1st Floor Leak Severity"
      unique_id: "water_leak_severity_1f"
      state: >
        {% set water_sensor = states.sensor.water_level_1f %}
        {% if water_sensor is not none %}
          {% set rapid_leak = water_sensor.attributes.get('consumption_15min_l_15min', 0) | float(0) %}
          {% set moderate_leak = water_sensor.attributes.get('consumption_30min_l_30min', 0) | float(0) %}
          {% set rapid_threshold = states('input_number.rapid_leak_threshold_tank_1f') | default(5.0) | float(5.0) %}
          {% set moderate_threshold = states('input_number.moderate_leak_threshold_tank_1f') | default(8.0) | float(8.0) %}
          {% if rapid_leak > rapid_threshold %}
            Critical
          {% elif moderate_leak > moderate_threshold %}
            Moderate
          {% else %}
            None
          {% endif %}
        {% else %}
          None
        {% endif %}
      device_class: "enum"
